import { AuthProvider } from '@/provider/AuthProvider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import { ThemeProvider } from '@/components/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'reydel-ecommerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <body className={inter.className}>
            <Header />
            {children}
            <footer>copyright reydel ecom 2023</footer>
          </body>
        </ThemeProvider>
      </AuthProvider>
    </html>
  );
}
